export enum IconType {
  ARROW_DOWN = 'icon__arrow-down',
  ARROW_DOWN_HOVER = 'icon__arrow-down--hover',
  ARROW_UP = 'icon__arrow-up',
  ARROW_UP_HOVER = 'icon__arrow-up--hover',
  CART = 'icon__cart',
  CART_HOVER = 'icon__cart--hover',
  CLOSE = 'icon__close',
  GEO_POINT = 'icon__geo-point',
  INSTAGRAM = 'icon__instagram',
  INSTAGRAM_HOVER = 'icon__instagram--hover',
  TWITTER = 'icon__twitter',
  TWITTER_HOVER = 'icon__twitter--hover',
  SOCIAL = 'icon__social',
  SOCIAL_HOVER = 'icon__social--hover',
  USER = 'icon__user',
  USER_HOVER = 'icon__user--hover',
  MAIL = 'icon__mail',
  MENU = 'icon__menu',
  PHONE = 'icon__phone',
  TICK = 'icon__tick',
}
